name: driver
description: A new Flutter project.

publish_to: "none"

version: 1.0.0+3

environment:
  sdk: ">=3.1.5 <4.0.0"

isar_version: &isar_version 3.1.0+1

dependencies:
  background_location: ^0.11.8
  badges: ^3.1.2
  bloc: ^8.1.2
  connectivity_plus: ^5.0.1
  cupertino_icons: ^1.0.6
  device_info_plus: ^9.1.0
  dio: ^5.3.3
  dio_cache_interceptor: ^3.4.4
  dropdown_search: ^5.0.6
  equatable: ^2.0.5
  firebase_core: ^2.22.0
  firebase_crashlytics: ^3.4.4
  firebase_messaging: ^14.7.4
  flutter:
    sdk: flutter
  flutter_bloc: ^8.1.3
  flutter_local_notifications: ^16.1.0
  flutter_localizations:
    sdk: flutter
  flutter_native_splash: ^2.3.5
  flutter_secure_storage: ^9.0.0
  geolocator: ^10.1.0
  get_it: ^7.6.4
  go_router: ^12.1.0
  google_fonts: ^6.1.0
  hydrated_bloc: ^9.1.2
  injectable: ^2.3.2
  intl: ^0.18.1
  isar: 3.1.0+1
  isar_flutter_libs: 3.1.0+1
  json_annotation: ^4.8.1
  logger: ^2.0.2+1
  path_provider: ^2.1.1
  permission_handler: ^11.0.1
  pin_code_fields: ^8.0.1
  pretty_dio_logger: ^1.3.1
  pull_to_refresh: ^2.0.0
  retrofit: ^4.0.3
  shared_preferences: ^2.2.2
  supercharged: ^2.1.1
  table_calendar: ^3.0.9
  tuple: ^2.0.2

dev_dependencies:
  bloc_test: ^9.1.5
  build_runner: ^2.4.6
  flutter_gen_runner: ^5.3.2
  flutter_launcher_icons: ^0.13.1
  flutter_test:
    sdk: flutter
  injectable_generator: ^2.4.1
  isar_generator: 3.1.0+1
  json_serializable: ^6.7.1
  lint: ^2.1.2
  retrofit_generator: ^8.0.3

flutter_gen:
  output: lib/generated/

flutter:
  generate: true

  uses-material-design: true

  assets:
    - assets/images/

  fonts:
    - family: Poppins
      fonts:
        - asset: assets/fonts/Poppins-Regular.ttf
        - asset: assets/fonts/Poppins-Medium.ttf
          weight: 500
        - asset: assets/fonts/Poppins-SemiBold.ttf
          weight: 600
        - asset: assets/fonts/Poppins-Bold.ttf
          weight: 700
        - asset: assets/fonts/Poppins-ExtraBold.ttf
          weight: 800
        - asset: assets/fonts/Poppins-Black.ttf
          weight: 900

flutter_intl:
  enabled: true
